2021-10-09 14:57:27,561 INFO    MainThread:25620 [wandb_setup.py:_flush():69] setting env: {}
2021-10-09 14:57:27,562 INFO    MainThread:25620 [wandb_setup.py:_flush():69] setting login settings: {'anonymous': 'must'}
2021-10-09 14:57:27,562 INFO    MainThread:25620 [wandb_init.py:_log_setup():342] Logging user logs to /home/inge/Pytorch-UNet/wandb/run-20211009_145727-2a3mdjj1/logs/debug.log
2021-10-09 14:57:27,562 INFO    MainThread:25620 [wandb_init.py:_log_setup():343] Logging internal logs to /home/inge/Pytorch-UNet/wandb/run-20211009_145727-2a3mdjj1/logs/debug-internal.log
2021-10-09 14:57:27,562 INFO    MainThread:25620 [wandb_init.py:init():375] calling init triggers
2021-10-09 14:57:27,563 INFO    MainThread:25620 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-10-09 14:57:27,563 INFO    MainThread:25620 [wandb_init.py:init():424] starting backend
2021-10-09 14:57:27,563 INFO    MainThread:25620 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-09 14:57:27,619 INFO    MainThread:25620 [backend.py:ensure_launched():135] starting backend process...
2021-10-09 14:57:27,632 INFO    MainThread:25620 [backend.py:ensure_launched():139] started backend process with pid: 25628
2021-10-09 14:57:27,639 INFO    MainThread:25620 [wandb_init.py:init():429] backend started and connected
2021-10-09 14:57:27,640 INFO    MainThread:25620 [wandb_init.py:init():477] updated telemetry
2021-10-09 14:57:27,640 INFO    MainThread:25620 [wandb_init.py:init():500] communicating current version
2021-10-09 14:57:28,713 INFO    MainThread:25620 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-09 14:57:28,713 INFO    MainThread:25620 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-09 14:57:29,070 INFO    MainThread:25620 [wandb_init.py:init():540] starting run threads in backend
2021-10-09 14:57:33,553 INFO    MainThread:25620 [wandb_run.py:_console_start():1601] atexit reg
2021-10-09 14:57:33,554 INFO    MainThread:25620 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.REDIRECT
2021-10-09 14:57:33,554 INFO    MainThread:25620 [wandb_run.py:_redirect():1480] Redirecting console.
2021-10-09 14:57:33,558 INFO    MainThread:25620 [wandb_run.py:_redirect():1536] Redirects installed.
2021-10-09 14:57:33,558 INFO    MainThread:25620 [wandb_init.py:init():565] run started, returning control to user process
2021-10-09 14:57:33,559 INFO    MainThread:25620 [wandb_run.py:_config_callback():843] config_cb None None {'epochs': 5, 'batch_size': 1, 'learning_rate': 1e-05, 'val_percent': 0.1, 'save_checkpoint': True, 'img_scale': 0.5, 'amp': False}
2021-10-09 14:57:33,731 INFO    MainThread:25620 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 1
2021-10-09 14:57:33,731 INFO    MainThread:25620 [wandb_run.py:_restore():1543] restore
2021-10-09 14:57:36,081 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-10-09 14:57:36,306 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 736
}

2021-10-09 14:57:37,200 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 4413
}

2021-10-09 14:57:37,303 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 8099
}

2021-10-09 14:57:37,407 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 736
  total_bytes: 8099
}

2021-10-09 14:57:37,509 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8099
  total_bytes: 8099
}

2021-10-09 14:57:37,611 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8099
  total_bytes: 8099
}

2021-10-09 14:57:37,716 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8099
  total_bytes: 8099
}

2021-10-09 14:57:37,819 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8099
  total_bytes: 8099
}

2021-10-09 14:57:37,921 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8099
  total_bytes: 8099
}

2021-10-09 14:57:38,128 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8099
  total_bytes: 8099
}

2021-10-09 14:57:38,230 INFO    MainThread:25620 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8099
  total_bytes: 8099
}

2021-10-09 14:57:39,356 INFO    MainThread:25620 [wandb_run.py:_show_files():1915] logging synced files
